# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
#https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# SITE CONFIGURATION
baseurl:
url: "https://www.inspirocreative.studio"

# THEME-SPECIFIC CONFIGURATION
title: "InspiroCreative"                                     # site's title
description: "A website about Making music and Art"      # used by search engines
avatar: assets/img/Stickers/olin.png          # Empty for no avatar in navbar
favicon: assets/img/Stickers/olin.ico                             # Icon displayed in the tab

# Header and footer text
header_text: "Dedicated to inspiring creativity and optimism for the younger generations" # Change Blog header text
header_feature_image: assets/img/Stickers/worldtree.png
footer_text: >
  Follow on:

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/Stickers/colorimg.png                  # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
cookie_consent_disclaimer: We would like to use third party cookies and scripts to improve the functionality of this website.
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*", ".travis.yml",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap
